language: ruby
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
before_install:
  - gem install bundler -v '1.17.3'
install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
script:
  - bundle exec rubocop
  - bundle exec rspec
